<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="events" nsURI="http://eclipse.org/rcptt/core/launching.ecore"
    nsPrefix="org.eclipse.rcptt.core.launching">
  <eClassifiers xsi:type="ecore:EClass" name="AutEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="AutEventInit" eSuperTypes="#//AutEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleState" upperBound="-1"
        eType="#//AutBundleState" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutEventStart" eSuperTypes="#//AutEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eclPort" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="teslaPort" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//AutStartState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="platform" eType="#//Platform"
        defaultValueLiteral="Other"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capability" eType="#//Capability"
        defaultValueLiteral="Other"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AutStartState">
    <eLiterals name="Ok"/>
    <eLiterals name="Fail"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutBundleState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutEventLocation" eSuperTypes="#//AutEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutEventPing" eSuperTypes="#//AutEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutEventPingResponse"/>
  <eClassifiers xsi:type="ecore:EClass" name="AutSendEvent" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//AutEvent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutReconnect" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="q7EclPort" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Platform">
    <eLiterals name="Other" literal="Other"/>
    <eLiterals name="MacOs" value="1"/>
    <eLiterals name="Windows" value="2"/>
    <eLiterals name="Linux" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Capability">
    <eLiterals name="Other"/>
    <eLiterals name="e3" value="1"/>
    <eLiterals name="e4" value="2"/>
    <eLiterals name="rap" value="3"/>
  </eClassifiers>
</ecore:EPackage>
