<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="commands"
    nsURI="http://www.eclipse.org/ecl/platform.ui/commands.ecore" nsPrefix="org.eclipse.rcptt.ecl.platform.ui">
  <eClassifiers xsi:type="ecore:EClass" name="Alert" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListWorkingSets" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Returns a list of all working sets available"/>
      <details key="returns" value="Working set objects"/>
      <details key="example" value="list-working-sets | foreach {delete-working-set}"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateWorkingSet" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Creates working set with a given name."/>
      <details key="returns" value="Nothing"/>
      <details key="example" value="create-working-set &quot;MyWorkingSet&quot;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/ecl/input"/>
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Working set name"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="org.eclipse.ui.resourceWorkingSetPage">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Working set type id. Default value is &lt;code>org.eclipse.ui.resourceWorkingSetPage&lt;/code>, which corresponds to Resource Working Set. The short name &lt;code>java&lt;/code> can be used to identify type &lt;code>org.eclipse.jdt.ui.JavaWorkingSetPage&lt;/code>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteWorkingSet" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Deletes working set"/>
      <details key="returns" value="Nothing"/>
      <details key="example" value="list-working-sets | foreach {delete-working-set}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="ecore:EClass objects.ecore#//WorkingSet">
      <eAnnotations source="http://www.eclipse.org/ecl/input"/>
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Working set object"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetWorkingSet">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Finds working set by name"/>
      <details key="returns" value="Working set object"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Working set name"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClearLogView" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Clears error log. If Error log is open, then it is closed before log clearing and then open again."/>
      <details key="returns" value="Nothing"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetHotkey" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandId" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SaveScreenshot" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Saves the screenshot."/>
      <details key="returns" value="Nothing"/>
      <details key="example" value="get-eclipse-window | get-object | save-screenshot [substitute-variables &quot;${workspace_loc}/images/actual.png&quot;]"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="out" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
