<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://eclipse.org/rcptt/core/ecl" nsPrefix="org.eclipse.rcptt.core.ecl.model">
  <eClassifiers xsi:type="ecore:EClass" name="EnterContext" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" eType="ecore:EClass ../../org.eclipse.rcptt.core.scenario/models/scenario.ecore#//Context"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateContext" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrepareEnvironment" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetCommandsDelay" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetQ7Information" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Q7Information">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="teslaActive" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="teslaPort" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clientActive" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="windowCount" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetQ7Features" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="features" upperBound="-1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetPerspectives" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerspectiveInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerspectivesList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="perspectives" upperBound="-1"
        eType="#//PerspectiveInfo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetViews" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//ViewInfo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//ViewInfo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateReport" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="q7info" eType="ecore:EClass ../../org.eclipse.rcptt.reporting/model/reporting.ecore#//Q7Info"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetReport" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeginReportNode" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.rcptt.watson.core/model/report.ecore#//PropertyMap"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndReportNode" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="snaphots" upperBound="-1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="takeSnaphots" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.rcptt.watson.core/model/report.ecore#//PropertyMap"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportAppend" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/ecl/input"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetQ7Option" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Sets Q7 runtime option."/>
      <details key="example" value="&lt;code>set-q7-option eclExecutionDelay 0&lt;/code>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="&lt;br/>&#xD;&#xA;Available keys:&#xD;&#xA;&lt;ul>&#xD;&#xA;    &lt;li> &lt;b>jobDebugjobTimeout&lt;/b> Eclipse job debug plugin jobs timeout (def: 300000 ms) &lt;/li>&#xD;&#xA;    &lt;li> &lt;b>jobSleepingStepTime&lt;/b> Step in step mode (def: 200 ms) &lt;/li>&#xD;&#xA;    &lt;li> &lt;b>jobSleepingStepTimeout&lt;/b> Stepping job timeout (def: 120000 ms) &lt;/li>&#xD;&#xA;    &lt;li> &lt;b>jobTreatAsSleepingTimeout&lt;/b> Enable Job step mode timeout (def: 10000 ms) &lt;/li>&#xD;&#xA;    &lt;li> &lt;b>jobHangTimeout&lt;/b> Job skip timeout (def: 30000 ms) &lt;/li>&#xD;&#xA;    &lt;li> &lt;b>jobScheduleDelayedMaxtime&lt;/b> Wait for jobs with delay less timeout (def: 600 ms) &lt;/li>&#xD;&#xA;    &lt;li> &lt;b>eclExecutionDelay&lt;/b> Wait for time between each ECL command (def: 0 ms) &lt;/li>&#xD;&#xA;    &lt;li> &lt;b>workspaceClearForceGc&lt;/b> Forces garbage collection on workspace cleanup (def: true) &lt;/li>&#xD;&#xA;&lt;/ul>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExecutionPhase">
    <eLiterals name="Auto"/>
    <eLiterals name="Start" value="1"/>
    <eLiterals name="Run" value="2"/>
    <eLiterals name="Finish" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecVerification" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verification" eType="ecore:EClass ../../org.eclipse.rcptt.core.scenario/models/scenario.ecore#//Verification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phase" eType="#//ExecutionPhase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResetVerifications" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateVerification" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateWidgetVerificationParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selector" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TerminateAut" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
  </eClassifiers>
</ecore:EPackage>
