<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="context"
    nsURI="http://eclipse.org/rcptt/ctx/ecl" nsPrefix="org.eclipse.rcptt.ctx.ecl">
  <eClassifiers xsi:type="ecore:EClass" name="EclContext" eSuperTypes="../../org.eclipse.rcptt.core.scenario/models/scenario.ecore#//Context">
    <eStructuralFeatures xsi:type="ecore:EReference" name="script" eType="ecore:EClass ../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Script"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
