def build
node {
  checkout scm
  result = load('releng/Jenkinsfile.groovy')(this)
  assert result != null
  build = result
}

pipeline {
  agent {
    kubernetes {
      label 'rcptt-build-and-deploy-agent-3.5.4'
      yaml build.YAML_BUILD_AND_DEPLOY_AGENT
    }
  }

  stages {
    stage('Start Build and Test') {
      steps {
        script {
          build.build_and_test(true)
        }
      }
    }
    stage('Deploy') {
      steps {
        script {
          build.deploy("Nightly")
        }
      }
    }
  }

  post {
    always {
      script {
        build.post_build_actions()
      }
    }
  }
}