<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="log" nsURI="http://eclipse.org/rcptt/verifications/log" nsPrefix="org.eclipse.rcptt.verifications.log">
  <eClassifiers xsi:type="ecore:EClass" name="LogEntryPredicate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severityMask" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="7"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pluginPattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=".*"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messagePattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=".*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorLogVerification" eSuperTypes="../../org.eclipse.rcptt.core.scenario/models/scenario.ecore#//Verification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allowed" upperBound="-1"
        eType="#//LogEntryPredicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="denied" upperBound="-1"
        eType="#//LogEntryPredicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="required" upperBound="-1"
        eType="#//LogEntryPredicate" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
