<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="commands"
    nsURI="http://www.eclipse.org/ecl/platform/commands.ecore" nsPrefix="platformCommands">
  <eClassifiers xsi:type="ecore:EClass" name="ListPlugins" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Returns list of all plugins."/>
      <details key="returns" value="Lists all available plugins. "/>
      <details key="example" value="list-plugins | foreach [val item]  {&#xA;&#xA;&#x9;if [$item | get name | matches &quot;Q7 ECL.*&quot;]{&#xA;    &#x9;&#x9;$item | get name | log&#xA;&#x9;}&#xA;}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeDependencies" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="When true, returned plugins includes information about imported packages and bundle dependencies."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListFeatures" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Returns list of all features."/>
      <details key="returns" value="Lists all available features. "/>
      <details key="example" value="list-features | foreach [val item]  {&#xA;&#x9;if [$item | get id | matches &quot;com.xored.q7.*&quot;]{&#xA;    &#x9;&#x9;$item | get name | log&#xA;&#x9;}&#xA;}"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListRepositories" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Returns list of p2 repositories."/>
      <details key="returns" value="List of p2 repositories"/>
      <details key="example" value="list-repositories | foreach [val item] {&#xA;&#x9;if [$item | get name | equals &quot;download cache&quot;]{&#xA;&#x9;&#x9;$item | get isArtifact | equals true | verify-true&#xA;&#x9;}&#xA;}&#xA;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddRepository" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Adds p2 repository."/>
      <details key="returns" value="nothing"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveRepository" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Removes p2 repository."/>
      <details key="returns" value="nothing"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateFeature" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Updates feature with defined name."/>
      <details key="returns" value="nothing"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateAll" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="SortBy" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Sorts list of objects from input stream by defined field. "/>
      <details key="returns" value="sorted list of objects"/>
      <details key="example" value="list-working-sets | sort-by -field name | foreach {get name | log}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="field" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListInstallUnits" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Returns list of all install units."/>
      <details key="returns" value="Lists all install units."/>
      <details key="example" value="list-install-units | write-lines -uri &quot;workspace:/Project/Folder/file.txt&quot;&#xA;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetLog" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Returns log entries sorted by timestamp descending."/>
      <details key="returns" value="Log entries"/>
      <details key="example" value="get-log -levels error | as-table-data | write-csv-file &quot;workspace:/Project/file2.csv&quot;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="levels" upperBound="-1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Log entry severities to show. Any of &lt;code>error&lt;/code>, &lt;code>warning&lt;/code>, &lt;code>info&lt;/code>, &lt;code>OK&lt;/code>, &lt;code>Cancel&lt;/code> in any letter case."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limit" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="100">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Number of log entries to get. Default value is 100."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Log" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Writes an entry into Eclipse log"/>
      <details key="returns" value="Nothing"/>
      <details key="example" value="log -message &quot;Error&quot; -severity error -plugin &quot;com.xored.q7&quot;&#xA;echo &quot;Warning&quot; | log -severity warning"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/ecl/input" references="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Foreach/input/%http:%2F%2Fwww.eclipse.org%2Fecl%2Finput%"/>
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Writes an entry into Eclipse log"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="info">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Log entry severity. Can be &lt;code>info&lt;/code>, &lt;code>warning&lt;/code>, &lt;code>error&lt;/code>, &lt;code>ok&lt;/code>, &lt;code>cancel&lt;/code> in any letter case. Default value is &lt;code>info&lt;/code>."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="plugin" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="org.eclipse.rcptt.ecl.platform">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="ID of plugin adding log entry. Default value is &lt;code>org.eclipse.rcptt.ecl.platform&lt;/code>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Echo" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Takes a string argument and writes it into an output pipe. "/>
      <details key="returns" value="value of &lt;code>str&lt;/code> argument"/>
      <details key="example" value="echo &quot;MyStr&quot; | log"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="">
      <eAnnotations source="http://www.eclipse.org/ecl/input"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClearLog" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Removes log file. Note that if log view is open, it may enter into inconsistent state. If it is important, use &lt;code>clear-log-view&lt;/code> instead"/>
      <details key="returns" value="Nothing"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListLaunchConfigurations" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Returns list of launch configurations."/>
      <details key="returns" value="List of launch configurations."/>
      <details key="example" value="list-launch-configurations | write-lines -uri &quot;workspace:/Project/Folder/file.txt&quot;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Launch" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="descriprion" value="Launches a configuration in specified mode. "/>
      <details key="returns" value="Nothing."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubstituteVariables" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Recursively resolves and replaces all variable references in the given expression with their corresponding values. Allows the client to control whether references to undefined variables are reported as an error (i.e. an exception is thrown). See &lt;a href='http://www.xored.com/2013/09/03/how-to-pass-a-value-to-a-test-during-its-execution/'>How to pass a value to a test&lt;/a> for more information."/>
      <details key="returns" value="expression with variable references replaced with variable values"/>
      <details key="example" value="//writes prop val to AUT workspace log&#xA;log [subsitute-variables &quot;${system_property:propertyName}&quot;] "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="expression referencing variables"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreUndefined" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="whether a reference to an undefined variable is to be considered an error (i.e. throw an exception)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetWorkspaceLocation" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="descriprion" value="Returns the path to workspace root."/>
      <details key="returns" value="path to workspace root"/>
      <details key="example" value="get-workspace-location | equals &quot;/Users/My_MacAir/aut-Q7-1.3.12-B2&quot; | verify-true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FindInWorkspace" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Perform regex search per segment. Returns list of matched paths."/>
      <details key="returns" value="list of matched paths"/>
      <details key="example" value="find-in-workspace &quot;project/dir1.*/dir2/file.*.txt&quot;"/>
      <details key="recorded" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="all" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
</ecore:EPackage>
