def build = library(
  identifier: 'rcptt-pipeline-library@groovy',
  retriever: modernSCM(
    [
      $class: 'GitSCMSource',
      remote: 'https://github.com/xored/rcptt.git'
    ]
  )
).org.eclipse.rcptt.jenkins.Build.new(this)

pipeline {
  agent {
    kubernetes {
      label 'rcptt-build-agent-3.5.4'
      yaml build.YAML_BUILD_AGENT
    }
  }

  stages {
    stage('Start Test') {
      steps {
        script {
          build.tests(TESTS, RUNNER, ARGS)
        }
      }
    }
  }

  post {
    always {
      script {
        build.post_build_actions()
      }
    }
  }
}