<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="raw" nsURI="http://eclipse.org/rcptt/tesla/rawprotocol" nsPrefix="org.eclipse.rpctt.tesla.rawprotocol">
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>&#xA;This class instances represent Tesla identifiers for UI elements (like widgets).&#xA;&lt;p>&#xA;Some Element identifier can be translated into the corresponding UIElement wrap (like SWTUIElement) by using&#xA;BasicElementMapper derivative (like SWTElementMapper).&#xA;&lt;p>&#xA;See BasicElementMapper.get(Element) method documentation for the details."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Response">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//ResponseStatus"
        defaultValueLiteral="Ok"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="advancedInformation" eType="ecore:EClass info.ecore#//AdvancedInformation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ResponseStatus">
    <eLiterals name="Ok"/>
    <eLiterals name="Failed" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandTransfer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" eType="#//Command"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//CommandTransferKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1"
        eType="ecore:EClass ui.ecore#//Widget" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rawEvents" upperBound="-1"
        eType="#//RawEvent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CommandTransferKind">
    <eLiterals name="Default"/>
    <eLiterals name="ReplacePrevious" value="1"/>
    <eLiterals name="InsertBeforeEssentialCommand" value="2"/>
    <eLiterals name="InsertBefore" value="3"/>
    <eLiterals name="Remove" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CloseConnection" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="TeslaScenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//Command" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementMapping" upperBound="-1"
        eType="#//CommandToElementEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredContexts" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rawMapping" upperBound="-1"
        eType="#//CommandToRawEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandToElementEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" eType="#//Command"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1"
        eType="ecore:EClass ui.ecore#//Widget" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandToRawEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rawEvents" upperBound="-1"
        eType="#//RawEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" eType="#//Command"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetFeatureResponse" eSuperTypes="#//Response">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetMode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//TeslaMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="widgetClasses" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TeslaMode">
    <eLiterals name="Features"/>
    <eLiterals name="Recording" value="1"/>
    <eLiterals name="Replay" value="2"/>
    <eLiterals name="Assertions" value="3"/>
    <eLiterals name="Pause" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecuteScenario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executeMode" eType="#//ExecuteMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StepExecution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExecuteMode">
    <eLiterals name="IMMEDIATE"/>
    <eLiterals name="STEPBYSTEP" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionStatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="progress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statusKind" eType="#//ExecutionStatusKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExecutionStatusKind">
    <eLiterals name="STARTED"/>
    <eLiterals name="RUNNING" value="1"/>
    <eLiterals name="FINISHED" value="2"/>
    <eLiterals name="CANCELED" value="3"/>
    <eLiterals name="PAUSED" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssertionFocus" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pointFixed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//Element"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageCapture" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RawEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="widget" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="detail" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="item" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="button" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="character" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateMask" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nativeEvent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResetAssertSelection"/>
</ecore:EPackage>
