<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nebula"
    nsURI="http://eclipse.org/rcptt/tesla/nebula" nsPrefix="org.eclipse.rcptt.tesla.nebula">
  <eClassifiers xsi:type="ecore:EClass" name="SetSelectionEx" eSuperTypes="../../org.eclipse.rcptt.tesla.core/models/protocol.ecore#//SetSelection"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetSelectionRange" eSuperTypes="../../org.eclipse.rcptt.tesla.core/models/protocol.ecore#//SetSelection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toPath" unique="false"
        upperBound="-1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//MultiSelectionItemEx"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//MultiSelectionItemEx"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiSelectionItemEx" eSuperTypes="../../org.eclipse.rcptt.tesla.core/models/protocol.ecore#//MultiSelectionItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cellColumn" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowHeader" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
