r = find("PackageExplo.png").below(60)
p = r.find("GeneralProject")
doubleClick(p)
doubleClick("WEFoderA.png")
click("filel.png")
keyDown(Key.CTRL)
hover("Eifile2.png")
click("Eifile2.png")
keyUp(Key.CTRL)
type(Key.DELETE)
click("1362046966820.png")
