<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ast" nsURI="http://www.eclipse.org/ecl/ast.ecore" nsPrefix="org.eclipse.rcptt.ecl.ast">
  <eClassifiers xsi:type="ecore:EClass" name="AstNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceID" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AstExec" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//Exec #//AstNode">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AstLiteral" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//LiteralParameter #//AstNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScriptProcessStatus" eSuperTypes="../../org.eclipse.rcptt.ecl.core/model/ecl.ecore#//ProcessStatus #//AstNode"/>
</ecore:EPackage>
